[package]
name = "macros"
version = "1.0.0"
edition = "2021"

[lib]
name = "macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0.23"
regex = "1.8.3"
syn = { version = "2.0.15", features = ["full"] }
